import { Stack } from '@chakra-ui/react'
import Head from 'next/head'
import { useEffect } from 'react'
import Layout from '../components/Layout'
import axios from 'axios'

export default function Home() {

  const getHome = async () => {
    await axios('http://localhost:8080')
  }
  useEffect(()=>{
    getHome()
  }, [])

  return (
    <Stack >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <h1>home</h1>
      </Layout>
    </Stack>
  )
}
